--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2
-- Dumped by pg_dump version 14.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public.tickets DROP CONSTRAINT tickets_galleries_id_fk;
ALTER TABLE ONLY public.tickets DROP CONSTRAINT tickets_currency_id_fk;
ALTER TABLE ONLY public.ticket_purchase_reports DROP CONSTRAINT ticket_purchase_reports_users_id_fk;
ALTER TABLE ONLY public.ticket_purchase_reports DROP CONSTRAINT ticket_purchase_reports_tickets_id_fk;
ALTER TABLE ONLY public.ticket_purchase_reports DROP CONSTRAINT ticket_purchase_reports_currency_id_fk;
ALTER TABLE ONLY public.pictures DROP CONSTRAINT pictures_text_painters_id_fk;
ALTER TABLE ONLY public.picture_purchase_reports DROP CONSTRAINT picture_purchase_reports_users_id_fk;
ALTER TABLE ONLY public.picture_purchase_reports DROP CONSTRAINT picture_purchase_reports_pictures_id_fk;
ALTER TABLE ONLY public.picture_purchase_reports DROP CONSTRAINT picture_purchase_reports_currency_id_fk;
DROP INDEX public.users_telephone_number_idx;
DROP INDEX public.users_login_unq;
DROP INDEX public.users_full_name_idx;
DROP INDEX public.tickets_gallery_id_idx;
DROP INDEX public.tickets_date_of_visit_idx;
DROP INDEX public.tickets_currency_id_idx;
DROP INDEX public.tickets_cost_idx;
DROP INDEX public.ticket_purchase_reports_visitor_id_idx;
DROP INDEX public.ticket_purchase_reports_ticket_id_idx;
DROP INDEX public.ticket_purchase_reports_date_of_purchase_idx;
DROP INDEX public.ticket_purchase_reports_currency_id_idx;
DROP INDEX public.ticket_purchase_reports_cost_idx;
DROP INDEX public.pictures_year_idx;
DROP INDEX public.pictures_painter_id_idx;
DROP INDEX public.pictures_name_idx;
DROP INDEX public.picture_purchase_reports_visitor_id_idx;
DROP INDEX public.picture_purchase_reports_picture_id_idx;
DROP INDEX public.picture_purchase_reports_date_of_purchase_idx;
DROP INDEX public.picture_purchase_reports_currency_id_idx;
DROP INDEX public.picture_purchase_reports_cost_idx;
DROP INDEX public.painters_telephone_number_idx;
DROP INDEX public.painters_full_name_idx;
DROP INDEX public.galleries_name_idx;
DROP INDEX public.galleries_address_idx;
DROP INDEX public.currency_name_unq;
DROP INDEX public.currency_code_unq;
ALTER TABLE ONLY public.users DROP CONSTRAINT users_pk;
ALTER TABLE ONLY public.tickets DROP CONSTRAINT tickets_pk;
ALTER TABLE ONLY public.ticket_purchase_reports DROP CONSTRAINT ticket_purchase_reports_pk;
ALTER TABLE ONLY public.pictures DROP CONSTRAINT pictures_pk;
ALTER TABLE ONLY public.picture_purchase_reports DROP CONSTRAINT picture_purchase_reports_pk;
ALTER TABLE ONLY public.painters DROP CONSTRAINT painters_pk;
ALTER TABLE ONLY public.galleries DROP CONSTRAINT galleries_pk;
ALTER TABLE ONLY public.currency DROP CONSTRAINT currency_pk;
DROP TABLE public.users;
DROP TABLE public.tickets;
DROP TABLE public.ticket_purchase_reports;
DROP SEQUENCE public.ticket_purchase_reports_id_seq;
DROP TABLE public.pictures;
DROP SEQUENCE public.pictures_id_seq;
DROP TABLE public.picture_purchase_reports;
DROP SEQUENCE public.picture_purchase_reports_id_seq;
DROP TABLE public.painters;
DROP TABLE public.galleries;
DROP TABLE public.currency;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: currency; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.currency (
    id integer NOT NULL,
    code integer,
    name character varying(3),
    description character varying(255)
);


ALTER TABLE public.currency OWNER TO postgres;

--
-- Name: currency_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.currency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: galleries; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.galleries (
    id integer NOT NULL,
    name character varying(255),
    address character varying(255)
);


ALTER TABLE public.galleries OWNER TO postgres;

--
-- Name: painters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.painters (
    id integer NOT NULL,
    full_name character varying(255),
    date_of_birth date,
    telephone_number character varying(30)
);


ALTER TABLE public.painters OWNER TO postgres;

--
-- Name: picture_purchase_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.picture_purchase_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.picture_purchase_reports_id_seq OWNER TO postgres;

--
-- Name: picture_purchase_reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.picture_purchase_reports (
    id integer DEFAULT nextval('public.picture_purchase_reports_id_seq'::regclass) NOT NULL,
    visitor_id integer,
    picture_id integer,
    date_of_purchase timestamp without time zone,
    cost integer,
    currency_id integer
);


ALTER TABLE public.picture_purchase_reports OWNER TO postgres;

--
-- Name: pictures_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.pictures_id_seq
    START WITH 68
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.pictures_id_seq OWNER TO postgres;

--
-- Name: pictures; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pictures (
    id integer DEFAULT nextval('public.pictures_id_seq'::regclass) NOT NULL,
    name character varying(255),
    painter_id integer,
    year date
);


ALTER TABLE public.pictures OWNER TO postgres;

--
-- Name: ticket_purchase_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ticket_purchase_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.ticket_purchase_reports_id_seq OWNER TO postgres;

--
-- Name: ticket_purchase_reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket_purchase_reports (
    id integer DEFAULT nextval('public.ticket_purchase_reports_id_seq'::regclass) NOT NULL,
    visitor_id integer,
    ticket_id integer,
    date_of_purchase timestamp without time zone,
    cost integer,
    currency_id integer
);


ALTER TABLE public.ticket_purchase_reports OWNER TO postgres;

--
-- Name: tickets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tickets (
    id integer NOT NULL,
    gallery_id integer,
    date_of_visit date,
    cost integer,
    currency_id integer
);


ALTER TABLE public.tickets OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    full_name character varying(255),
    date_of_birth date,
    telephone_number character varying(30),
    login character varying(50) DEFAULT NULL::character varying,
    password character varying(60) DEFAULT NULL::character varying,
    role character varying(60) DEFAULT (NOT NULL::boolean) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: currency currency_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_pk PRIMARY KEY (id);


--
-- Name: galleries galleries_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.galleries
    ADD CONSTRAINT galleries_pk PRIMARY KEY (id);


--
-- Name: painters painters_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.painters
    ADD CONSTRAINT painters_pk PRIMARY KEY (id);


--
-- Name: picture_purchase_reports picture_purchase_reports_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.picture_purchase_reports
    ADD CONSTRAINT picture_purchase_reports_pk PRIMARY KEY (id);


--
-- Name: pictures pictures_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pictures
    ADD CONSTRAINT pictures_pk PRIMARY KEY (id);


--
-- Name: ticket_purchase_reports ticket_purchase_reports_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_purchase_reports
    ADD CONSTRAINT ticket_purchase_reports_pk PRIMARY KEY (id);


--
-- Name: tickets tickets_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pk PRIMARY KEY (id);


--
-- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pk PRIMARY KEY (id);


--
-- Name: currency_code_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX currency_code_unq ON public.currency USING btree (code);


--
-- Name: currency_name_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX currency_name_unq ON public.currency USING btree (name);


--
-- Name: galleries_address_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX galleries_address_idx ON public.galleries USING btree (address);


--
-- Name: galleries_name_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX galleries_name_idx ON public.galleries USING btree (name);


--
-- Name: painters_full_name_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX painters_full_name_idx ON public.painters USING btree (full_name);


--
-- Name: painters_telephone_number_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX painters_telephone_number_idx ON public.painters USING btree (telephone_number);


--
-- Name: picture_purchase_reports_cost_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX picture_purchase_reports_cost_idx ON public.picture_purchase_reports USING btree (cost);


--
-- Name: picture_purchase_reports_currency_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX picture_purchase_reports_currency_id_idx ON public.picture_purchase_reports USING btree (currency_id);


--
-- Name: picture_purchase_reports_date_of_purchase_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX picture_purchase_reports_date_of_purchase_idx ON public.picture_purchase_reports USING btree (date_of_purchase);


--
-- Name: picture_purchase_reports_picture_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX picture_purchase_reports_picture_id_idx ON public.picture_purchase_reports USING btree (picture_id);


--
-- Name: picture_purchase_reports_visitor_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX picture_purchase_reports_visitor_id_idx ON public.picture_purchase_reports USING btree (visitor_id);


--
-- Name: pictures_name_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pictures_name_idx ON public.pictures USING btree (name);


--
-- Name: pictures_painter_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pictures_painter_id_idx ON public.pictures USING btree (painter_id);


--
-- Name: pictures_year_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pictures_year_idx ON public.pictures USING btree (year);


--
-- Name: ticket_purchase_reports_cost_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ticket_purchase_reports_cost_idx ON public.ticket_purchase_reports USING btree (cost);


--
-- Name: ticket_purchase_reports_currency_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ticket_purchase_reports_currency_id_idx ON public.ticket_purchase_reports USING btree (currency_id);


--
-- Name: ticket_purchase_reports_date_of_purchase_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ticket_purchase_reports_date_of_purchase_idx ON public.ticket_purchase_reports USING btree (date_of_purchase);


--
-- Name: ticket_purchase_reports_ticket_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ticket_purchase_reports_ticket_id_idx ON public.ticket_purchase_reports USING btree (ticket_id);


--
-- Name: ticket_purchase_reports_visitor_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ticket_purchase_reports_visitor_id_idx ON public.ticket_purchase_reports USING btree (visitor_id);


--
-- Name: tickets_cost_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tickets_cost_idx ON public.tickets USING btree (cost);


--
-- Name: tickets_currency_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tickets_currency_id_idx ON public.tickets USING btree (currency_id);


--
-- Name: tickets_date_of_visit_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tickets_date_of_visit_idx ON public.tickets USING btree (date_of_visit);


--
-- Name: tickets_gallery_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tickets_gallery_id_idx ON public.tickets USING btree (gallery_id);


--
-- Name: users_full_name_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_full_name_idx ON public.users USING btree (full_name);


--
-- Name: users_login_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX users_login_unq ON public.users USING btree (login);


--
-- Name: users_telephone_number_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_telephone_number_idx ON public.users USING btree (telephone_number);


--
-- Name: picture_purchase_reports picture_purchase_reports_currency_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.picture_purchase_reports
    ADD CONSTRAINT picture_purchase_reports_currency_id_fk FOREIGN KEY (currency_id) REFERENCES public.currency(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: picture_purchase_reports picture_purchase_reports_pictures_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.picture_purchase_reports
    ADD CONSTRAINT picture_purchase_reports_pictures_id_fk FOREIGN KEY (picture_id) REFERENCES public.pictures(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: picture_purchase_reports picture_purchase_reports_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.picture_purchase_reports
    ADD CONSTRAINT picture_purchase_reports_users_id_fk FOREIGN KEY (visitor_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: pictures pictures_text_painters_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pictures
    ADD CONSTRAINT pictures_text_painters_id_fk FOREIGN KEY (painter_id) REFERENCES public.painters(id) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: ticket_purchase_reports ticket_purchase_reports_currency_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_purchase_reports
    ADD CONSTRAINT ticket_purchase_reports_currency_id_fk FOREIGN KEY (currency_id) REFERENCES public.currency(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: ticket_purchase_reports ticket_purchase_reports_tickets_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_purchase_reports
    ADD CONSTRAINT ticket_purchase_reports_tickets_id_fk FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: ticket_purchase_reports ticket_purchase_reports_users_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket_purchase_reports
    ADD CONSTRAINT ticket_purchase_reports_users_id_fk FOREIGN KEY (visitor_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: tickets tickets_currency_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_currency_id_fk FOREIGN KEY (currency_id) REFERENCES public.currency(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: tickets tickets_galleries_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_galleries_id_fk FOREIGN KEY (gallery_id) REFERENCES public.galleries(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

